# Adapted from create-t3-app.

name: Release - Beta

on:
  pull_request:
    types: [labeled]
    branches:
      - main
jobs:
  prerelease:
    if: |
      github.repository_owner == 'hngngn' &&
      contains(github.event.pull_request.labels.*.name, '🚀 autorelease')
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use BUN
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun i

      - name: Modify package.json version
        run: node .github/version-script-beta.mjs

      - name: Authenticate to NPM
        run: echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" >> .npmrc
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish Beta to NPM
        run: bun --filter shadcn-solid build && cd packages/cli && npm publish --tag beta

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/cli

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-shadcn-solid@${{ steps.package-version.outputs.current-version }}-pr-${{ github.event.number }} # encode the PR number into the artifact name
          path: packages/cli/dist/index.js